// Generated by CoffeeScript 1.3.3
(function() {
  var typo;

  typo = function(message, input, spec) {
    return console.log('typo called');
  };

  typo.is = function(input, spec) {
    return console.log('typo.is called');
  };

  typo.version = '0.0.1';

  module.exports = typo;

}).call(this);
